2022-01-03 15:46:06,232 :: INFO :: Training stdgi ||  interpolate False || attention decoder False || epochs 20 || lr 0.005






























 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 30/31 [01:22<00:02,  2.71s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:24<00:00,  2.73s/it]
Traceback (most recent call last):
  File "train_attention_stdgi.py", line 153, in <module>
    wandb.log("stdgi_loss", loss)
  File "/home/aiotlabws/Workspace/Env/anaconda3/envs/longnd/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1308, in log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary